# -*- coding: utf-8 -*-
"""fastai model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JvEq1V2PXX7faevDT59eozuH9twVbwtr
"""

import argparse
from fastai import *
from fastai.vision import *

import argparse


# Initialize parser
parser = argparse.ArgumentParser()

# Adding optional argument
parser.add_argument("-m", "--model", help="Model Path")
parser.add_argument("-i", "--image")

# Read arguments from command line
args = parser.parse_args()

im_path = args.image

model_path = args.model

learn = load_learner(model_path, "model.pkl")

pred = learn.predict(open_image(im_path))[2].numpy().tolist()

print(pred)


# # Initialize parser
# parser = argparse.ArgumentParser()

# # Adding optional argument
# parser.add_argument("-m", "--model", help="Model Path")
# parser.add_argument("-i", "--image")

# # Read arguments from command line
# args = parser.parse_args()

# im_path = args.image

# model_path = args.model

# learn = load_learner(model_path, "model.pkl")


# pred = learn.predict(open_image(im_path))[2].numpy().tolist()

# print(pred)

# #!python / content/script.py - -image '/content/drive/MyDrive/index.jpg' - -model '/content/drive/MyDrive'
